[package]
name = "syndica"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {version = "0.8.4", features = ["macros", "json"] }
# axum_macros = "0.5.0"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.14"
